import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/comps_ui/app-sidebar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Menu } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <SidebarProvider className="flex justify-start items-start">
          <AppSidebar />

          <main className="">
            <section></section>
            <section className="md:hidden dark:bg-neutral-950 overflow-hidden h-full  flex flex-col  flex-1/4 w-60 absolute top-0 right-0">
              <div className="flex justify-between">
                <span></span>
                <Menu className="m-2">close</Menu>
              </div>
              <div>
                <p className="p-2 font-bold text-leading">Link 1</p>
                <p className="p-2 font-bold text-leading">Link 2</p>
                <p className="p-2 font-bold text-leading">Link 3</p>
                <p className="p-2 font-bold text-leading">Link 4</p>
                <p className="p-2 font-bold text-leading">Link 5</p>
              </div>
            </section>
            <SidebarTrigger />

            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}




